terraform-1
Otus-DevOps-2022-11/mksmvskv_infra pull request #7
Opened 2023-01-26 08:50 UTC by mksmvskv

У меня возникла проблема, я никак не могу запустить terraform apply используя json ключ сервисного аккаунта, я генерил ключ и на сайте и через CLI, ничего не помогает, просто ругается, как только выставляю вместо него токен, все окей. Я делаю дз на WSL, но коллеги по группе так же используют и не сталкивались с проблемой.

И ещё один вариант, после создания и чекаута на новую ветку, мне нужно удалять старые файлы, что бы не тащить мусор в гитхаб?

# Выполнено ДЗ № 8

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
Все что написано в ДЗ, без дополнительных задач

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-01-28 14:28 UTC, mrgreyves requested changes
Здравствуйте!)
Касательно ваших вопросов - может быть вы сделали ключик с некорректными правами?
Если с ним совсем не получается, то стоит использовать токен доступа как вы и писали
Так же нужно поправить проблемы с пакером
ДЗ возвращаю на доработку

2023-01-28 14:28 UTC, mrgreyves commented on terraform/main.tf
> +terraform {
Описание провайдера перед пушем закомментируйте =)

2023-01-28 14:30 UTC, mrgreyves commented
По поводу удаления файлов - не очень понял что вы имеете ввиду. 
Кажется что ничего удалять не надо.

2023-01-28 14:32 UTC, mksmvskv commented
> По поводу удаления файлов - не очень понял что вы имеете ввиду. Кажется что ничего удалять не надо.

В плане в ветке все файлы с предыдущих дз.
А что вы имеете введу "поправить проблемы с пакером" немного не допонял.

2023-01-28 14:38 UTC, mksmvskv commented on terraform/main.tf
> +terraform {
> В плане в ветке все файлы с предыдущих дз. А что вы имеете введу "поправить проблемы с пакером" немного не допонял.
К слову про ключ, пакер у меня отрабатывает с ключем ранее созданным. Хотя я не проверял повторно.
Пользователей я уже по 10 раз пересоздавал с разными правами доступа в плоть до админа.

2023-01-28 15:49 UTC, mksmvskv commented
Поправил, проверьте Пожалуйста!

2023-01-29 15:36 UTC, mrgreyves approved these changes
Здравствуйте!)
С дз все хорошо
По вашу вопросу про гит - ничего подчищать в ветках не надо
Так и должно быть

2023-02-02 16:09 UTC, merged