Terraform 2
Otus-DevOps-2022-11/mksmvskv_infra pull request #8
Opened 2023-02-07 08:04 UTC by mksmvskv

# Выполнено ДЗ №8

 - [ X] Основное ДЗ
 - [ ] Задание со * (Только одно)

Выполнил ДЗ, и Часть со звездочкой. Честно, не очень нравится разбираться с Actions почему он заваливается.
Код написан правильно, у меня он отрабатывает. Задание со звездочкой я одно сделал, то, в котором нужно хранить в корзине стейт. Но при проверке Actions  у меня вылетает ошибка с папкой, которой быть и не должно) И с ошибками в коде, хотя все прекрасно работает у меня.

2023-02-08 12:13 UTC, mrgreyves requested changes
Здравствуйте!
В wf как раз бегают тесты которые валидируют конфиг
При этом у вас не рабочий код
Нужно поправить

2023-02-08 12:13 UTC, mrgreyves commented on terraform/stage/main.tf
> +backend "s3" {
Вот тут описания бекэнда быть не должно =)

2023-02-11 15:47 UTC, mrgreyves requested changes
Здравствуйте!)
![image](https://user-images.githubusercontent.com/34331259/218267441-67d90e4c-c566-49ab-9240-76f816fd3aec.png)
Вам нужно добавить модуль для создания VPC и файл с переменными

2023-02-11 15:50 UTC, mksmvskv commented
> Здравствуйте!) ![image](https://user-images.githubusercontent.com/34331259/218267441-67d90e4c-c566-49ab-9240-76f816fd3aec.png) Вам нужно добавить модуль для создания VPC и файл с переменными

Но в домашнем задании сказано удалить VPC, далее по тексту нет повторения что нужно "создать папку" а написано использовать переменные 
![image](https://user-images.githubusercontent.com/102152483/218267616-7217d0e7-c132-4221-9452-546f804b486d.png)

2023-02-18 13:05 UTC, mksmvskv commented
> Здравствуйте!) ![image](https://user-images.githubusercontent.com/34331259/218267441-67d90e4c-c566-49ab-9240-76f816fd3aec.png) Вам нужно добавить модуль для создания VPC и файл с переменными

Прошу проверить

2023-02-22 08:38 UTC, mrgreyves requested changes
Здравствуйте!)
Уже почти все хорошо
Дополнительно добавьте  terraform/storage-bucket.tf
Базовое описание хранения стейта, в нем как раз указывается путь до S3 яндекса
Фактически это небольшие правки, много времени на это не уйдет

2023-02-22 08:38 UTC, mrgreyves commented on terraform/terraform.tfvars.example
> -token = "y0_AgAAAAARN"
Если вы его удалили, то надобно вернуть обратно =)

2023-02-27 14:33 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2023-03-01 21:07 UTC, merged